version: "3.9"
services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: workerapp_api
    environment:
      # Persist DB inside a mounted volume directory
      - DATABASE_URL=sqlite:////app/data/test.db
    volumes:
      - data_volume:/app/data
    ports:
      - "8000:8000"

  web:
    image: nginx:1.27-alpine
    container_name: workerapp_web
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./services/web/dist:/usr/share/nginx/html:ro
      - ./services/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  data_volume:
